import events from './eventInterface';

const eventData: events[] = [
  new events(
    {
      id: 1,
      name: "Sân Thành Thắng",
      date: "Thứ 7, 20/12/2024, 17:30",
      host: "Trà Minh Trọng",
      playersNeeded: 5,
      level: "Trung bình khá",
      price: "25k",
      description: "",
      sport: "PickleBall",
      province: "Hồ Chí Minh",
      district: "Quận 12",
    },
  ),
  new events(
    {
      id: 2,
      name: "Sân Bình Minh",
      date: "Chủ nhật, 21/12/2024, 18:00",
      host: "Nguyễn Văn An",
      playersNeeded: 8,
      level: "Cao",
      price: "50k",
      description: "Cần thêm người để đủ sân.",
      sport: "Badminton",
      province: "Hồ Chí Minh",
      district: "Quận 1",
    },
  ),
  new events(
    {
      id: 3,
      name: "Sân Ngọc Thảo",
      date: "Thứ 2, 22/12/2024, 19:00",
      host: "Lê Hải Đăng",
      playersNeeded: 4,
      level: "Trung bình",
      price: "20k",
      description: "Tham gia giao lưu vui vẻ.",
      sport: "Football",
      province: "Thủ Đức",
      district: "Quận 9",
    },
  ),
  new events(
    {
      id: 4,
      name: "Sân Đại Học Thể Thao",
      date: "Thứ 4, 24/12/2024, 18:30",
      host: "Phạm Hoàng Phúc",
      playersNeeded: 6,
      level: "Cao",
      price: "30k",
      description: "Tìm thêm thành viên để giao lưu.",
      sport: "Basketball",
      province: "Hồ Chí Minh",
      district: "Quận Thủ Đức",
    },
  ),
  new events(
    {
      id: 5,
      name: "Sân Hoàng Gia",
      date: "Thứ 3, 23/12/2024, 20:00",
      host: "Nguyễn Hồng Sơn",
      playersNeeded: 5,
      level: "Trung bình khá",
      price: "25k",
      description: "",
      sport: "Tennis",
      province: "Đồng Nai",
      district: "Biên Hòa",
    },
  ),
  new events(
    {
      id: 6,
      name: "Sân Tân Bình",
      date: "Thứ 5, 25/12/2024, 19:30",
      host: "Lê Văn Hùng",
      playersNeeded: 7,
      level: "Cao",
      price: "40k",
      description: "Cần người chơi ổn định.",
      sport: "Football",
      province: "Hồ Chí Minh",
      district: "Quận Tân Bình",
    },
  ),
  new events(
    {
      id: 7,
      name: "Sân Kỳ Đồng",
      date: "Thứ 6, 26/12/2024, 17:00",
      host: "Trần Thị Lan",
      playersNeeded: 6,
      level: "Trung bình",
      price: "20k",
      description: "Mọi người cùng vui là chính.",
      sport: "PickleBall",
      province: "Hồ Chí Minh",
      district: "Quận 3",
    },
  ),
  new events(
    {
      id: 8,
      name: "Sân Đầm Sen",
      date: "Thứ 7, 27/12/2024, 18:30",
      host: "Phan Thanh Bình",
      playersNeeded: 4,
      level: "Khá",
      price: "50k",
      description: "Tìm bạn chơi chuyên nghiệp hơn.",
      sport: "Badminton",
      province: "Hồ Chí Minh",
      district: "Quận Tân Phú",
    },
  ),
  new events(
    {
      id: 9,
      name: "Sân Cầu Xanh",
      date: "Chủ nhật, 28/12/2024, 20:00",
      host: "Ngô Văn Quý",
      playersNeeded: 3,
      level: "Cao",
      price: "60k",
      description: "Cần tay chơi mạnh.",
      sport: "Tennis",
      province: "Bình Dương",
      district: "Thủ Dầu Một",
    },
  ),
  new events(
    {
      id: 10,
      name: "Sân Thể Thao Quận 4",
      date: "Thứ 3, 30/12/2024, 18:00",
      host: "Nguyễn Minh Tâm",
      playersNeeded: 8,
      level: "Trung bình khá",
      price: "15k",
      description: "",
      sport: "Football",
      province: "Hồ Chí Minh",
      district: "Quận 4",
    },
  ),
  new events(
    {
      id: 11,
      name: "Sân CLB Văn Hóa",
      date: "Thứ 5, 02/01/2025, 19:00",
      host: "Đỗ Thanh Nhã",
      playersNeeded: 5,
      level: "Khá",
      price: "30k",
      description: "Giao lưu bạn bè đầu năm.",
      sport: "Basketball",
      province: "Hồ Chí Minh",
      district: "Quận 7",
    },
  ),
  new events(
    {
      id: 12,
      name: "Sân Bạch Đằng",
      date: "Thứ 6, 03/01/2025, 18:30",
      host: "Hoàng Văn Long",
      playersNeeded: 6,
      level: "Trung bình khá",
      price: "20k",
      description: "Vui vẻ là chính.",
      sport: "Basketball",
      province: "Hồ Chí Minh",
      district: "Quận Bình Thạnh",
    },
  ),
];

export default eventData;